#!/usr/bin/env python3
import csv
from pathlib import Path


AUTHORITY_CSV = Path("entity_authority.csv")
ALIAS_CSV = Path("entity_alias.csv")
RULE_CSV = Path("ner_rule.csv")


AUTHORITY_ROWS = [
    # Main people
    ("person_jia_baoyu", "賈寶玉", "PERSON", "main_character", "賈政、王夫人之子，小說核心人物。"),
    ("person_lin_daiyu", "林黛玉", "PERSON", "main_character", "林如海、賈敏之女，賈母外孫女。"),
    ("person_xue_baochai", "薛寶釵", "PERSON", "main_character", "薛姨媽之女，薛蟠之妹。"),
    ("person_wang_xifeng", "王熙鳳", "PERSON", "main_character", "賈璉之妻，王夫人內侄女。"),
    ("person_jia_mu", "賈母", "PERSON", "elder", "史太君，賈府最高長輩。"),
    ("person_shi_xiangyun", "史湘雲", "PERSON", "main_character", "賈母娘家史氏親族女子。"),
    ("person_miaoyu", "妙玉", "PERSON", "main_character", "櫳翠庵中帶髮修行女子。"),
    ("person_jia_yuanchun", "賈元春", "PERSON", "main_character", "賈政長女，入宮為妃。"),
    ("person_jia_yingchun", "賈迎春", "PERSON", "main_character", "賈赦之女。"),
    ("person_jia_tanchun", "賈探春", "PERSON", "main_character", "賈政庶女。"),
    ("person_jia_xichun", "賈惜春", "PERSON", "main_character", "寧府賈珍之妹。"),
    ("person_li_wan", "李紈", "PERSON", "main_character", "賈珠之妻，賈蘭之母。"),
    ("person_qin_keqing", "秦可卿", "PERSON", "main_character", "賈蓉之妻。"),
    ("person_jia_lian", "賈璉", "PERSON", "main_character", "賈赦之子，王熙鳳之夫。"),
    ("person_jia_zheng", "賈政", "PERSON", "family_elder", "賈寶玉之父。"),
    ("person_wang_furen", "王夫人", "PERSON", "family_elder", "賈寶玉之母。"),
    ("person_xue_yima", "薛姨媽", "PERSON", "family_elder", "薛寶釵之母，王夫人之妹。"),
    ("person_jia_she", "賈赦", "PERSON", "family_elder", "賈母長子。"),
    ("person_jia_zhen", "賈珍", "PERSON", "family_elder", "寧國府主事者。"),
    ("person_jia_rong", "賈蓉", "PERSON", "family_member", "賈珍之子，秦可卿之夫。"),
    ("person_jia_huan", "賈環", "PERSON", "family_member", "賈政庶子。"),
    ("person_jia_lan", "賈蘭", "PERSON", "family_member", "賈珠、李紈之子。"),
    ("person_jia_min", "賈敏", "PERSON", "family_member", "林黛玉之母。"),
    ("person_lin_ruhai", "林如海", "PERSON", "family_member", "林黛玉之父。"),
    ("person_xue_pan", "薛蟠", "PERSON", "family_member", "薛寶釵之兄。"),
    ("person_xiangling", "香菱", "PERSON", "servant_concubine", "甄英蓮後名，薛蟠妾。"),
    ("person_zhen_shiyin", "甄士隱", "PERSON", "opening_character", "第一回人物，甄英蓮之父。"),
    ("person_jia_yucun", "賈雨村", "PERSON", "official", "貫穿前後的士人、官員。"),
    ("person_leng_zixing", "冷子興", "PERSON", "secondary", "演說榮國府者。"),
    ("person_liu_laolao", "劉姥姥", "PERSON", "secondary", "鄉村老婦，數入榮國府。"),
    # Servants and secondary women
    ("person_xiren", "襲人", "PERSON", "maid", "賈寶玉身邊丫鬟。"),
    ("person_qingwen", "晴雯", "PERSON", "maid", "賈寶玉身邊丫鬟。"),
    ("person_she_yue", "麝月", "PERSON", "maid", "賈寶玉身邊丫鬟。"),
    ("person_qiuwen", "秋紋", "PERSON", "maid", "賈寶玉身邊丫鬟。"),
    ("person_zijuan", "紫鵑", "PERSON", "maid", "林黛玉丫鬟。"),
    ("person_xueyan", "雪雁", "PERSON", "maid", "林黛玉丫鬟。"),
    ("person_ying_er", "鶯兒", "PERSON", "maid", "薛寶釵丫鬟。"),
    ("person_ping_er", "平兒", "PERSON", "maid", "王熙鳳陪房丫鬟。"),
    ("person_yuanyang", "鴛鴦", "PERSON", "maid", "賈母身邊丫鬟。"),
    ("person_siqi", "司棋", "PERSON", "maid", "迎春丫鬟。"),
    ("person_shishu", "侍書", "PERSON", "maid", "探春丫鬟。"),
    ("person_ruhua", "入畫", "PERSON", "maid", "惜春丫鬟。"),
    ("person_jinchuan", "金釧", "PERSON", "maid", "王夫人丫鬟。"),
    ("person_yuchuan", "玉釧", "PERSON", "maid", "王夫人丫鬟。"),
    ("person_you_erjie", "尤二姐", "PERSON", "secondary", "尤氏姐妹之一。"),
    ("person_you_sanjie", "尤三姐", "PERSON", "secondary", "尤氏姐妹之一。"),
    ("person_you_shi", "尤氏", "PERSON", "family_member", "賈珍之妻。"),
    ("person_zhao_yiniang", "趙姨娘", "PERSON", "concubine", "賈政妾，賈環、探春之母。"),
    ("person_zhou_rui_jia", "周瑞家的", "PERSON", "servant", "王夫人陪房。"),
    ("person_lai_da", "賴大", "PERSON", "servant", "賈府管家。"),
    # Myth / religion
    ("myth_nvwa", "女媧", "RELIGION_MYTH", "deity", "補天神話人物。"),
    ("myth_jinghuan_xianzi", "警幻仙子", "RELIGION_MYTH", "deity", "太虛幻境主者。"),
    ("myth_mangmang_dashi", "茫茫大士", "RELIGION_MYTH", "monk", "開篇神話人物。"),
    ("myth_miaomiao_zhenren", "渺渺真人", "RELIGION_MYTH", "daoist", "開篇神話人物。"),
    # Places / spaces
    ("place_jinling", "金陵", "PLACE", "city", "重要地名。"),
    ("place_yangzhou", "揚州", "PLACE", "city", "林如海任所。"),
    ("place_gusu", "姑蘇", "PLACE", "city", "甄士隱居處。"),
    ("place_changmen", "閶門", "PLACE", "gate_area", "姑蘇地名。"),
    ("place_daguanyuan", "大觀園", "PLACE", "garden", "賈府園林空間。"),
    ("building_rongguofu", "榮國府", "BUILDING", "mansion", "賈府之一。"),
    ("building_ningguofu", "寧國府", "BUILDING", "mansion", "賈府之一。"),
    ("building_yihongyuan", "怡紅院", "BUILDING", "residence", "賈寶玉居所。"),
    ("building_xiaoxiangguan", "瀟湘館", "BUILDING", "residence", "林黛玉居所。"),
    ("building_hengwuyuan", "蘅蕪苑", "BUILDING", "residence", "薛寶釵居所。"),
    ("building_qiushuangzhai", "秋爽齋", "BUILDING", "residence", "賈探春相關空間。"),
    ("building_daoxiangcun", "稻香村", "BUILDING", "residence", "李紈居所。"),
    ("building_nuanxiangwu", "暖香塢", "BUILDING", "garden_space", "大觀園空間。"),
    ("building_longcui_an", "櫳翠庵", "BUILDING", "temple", "妙玉所在。"),
    ("building_tiexian_si", "鐵檻寺", "BUILDING", "temple", "寺廟空間。"),
    ("building_hulu_miao", "葫蘆廟", "BUILDING", "temple", "甄士隱鄰近古廟。"),
    ("space_shufang", "書房", "ROOM_SPACE", "room", "室內空間。"),
    ("space_neishi", "內室", "ROOM_SPACE", "room", "室內空間。"),
    ("space_yuanzi", "園子", "ROOM_SPACE", "garden_space", "泛稱園林空間。"),
    ("space_langxia", "廊下", "ROOM_SPACE", "corridor", "建築空間。"),
    # Objects / motifs
    ("object_tongling_baoyu", "通靈寶玉", "OBJECT", "symbolic_object", "賈寶玉所銜之玉。"),
    ("object_fengyue_baojian", "風月寶鑑", "OBJECT", "symbolic_object", "具有象徵意義之物。"),
    ("object_baoyu", "寶玉", "OBJECT", "jade", "玉石物件；需與人物賈寶玉消歧。"),
    ("object_shanzi", "扇子", "OBJECT", "daily_object", "日用物件。"),
    ("object_chai", "釵", "OBJECT", "ornament", "女性飾物。"),
    ("object_yu", "玉", "OBJECT", "jade", "重要物象。"),
    # Motif-like concrete entities
    ("plant_haitang", "海棠", "FLOWER", "flower", "重要花木意象。"),
    ("plant_juhua", "菊花", "FLOWER", "flower", "詩社與花木意象。"),
    ("plant_furong", "芙蓉", "FLOWER", "flower", "花木意象。"),
    ("plant_taohua", "桃花", "FLOWER", "flower", "花木意象。"),
    ("plant_meihua", "梅花", "FLOWER", "flower", "花木意象。"),
    ("plant_mudan", "牡丹", "FLOWER", "flower", "花木意象。"),
    ("plant_lian", "蓮", "FLOWER", "flower", "花木意象。"),
    ("plant_zhu", "竹", "PLANT", "plant", "植物意象。"),
    ("plant_liu", "柳", "PLANT", "plant", "植物意象。"),
    ("plant_jiaoqiangwei", "薔薇", "FLOWER", "flower", "花木意象。"),
]


ALIAS_ROWS = [
    # canonical aliases
    ("寶玉", "person_jia_baoyu", "short_name", 100, "常用人物簡稱；與物件寶玉需依上下文消歧。"),
    ("寶二爺", "person_jia_baoyu", "title_alias", 100, ""),
    ("怡紅公子", "person_jia_baoyu", "literary_alias", 80, ""),
    ("林黛玉", "person_lin_daiyu", "full_name", 100, ""),
    ("黛玉", "person_lin_daiyu", "short_name", 100, ""),
    ("林姑娘", "person_lin_daiyu", "title_alias", 95, ""),
    ("顰兒", "person_lin_daiyu", "nickname", 90, ""),
    ("瀟湘妃子", "person_lin_daiyu", "literary_alias", 80, ""),
    ("薛寶釵", "person_xue_baochai", "full_name", 100, ""),
    ("寶釵", "person_xue_baochai", "short_name", 100, ""),
    ("寶姑娘", "person_xue_baochai", "title_alias", 85, ""),
    ("蘅蕪君", "person_xue_baochai", "literary_alias", 80, ""),
    ("王熙鳳", "person_wang_xifeng", "full_name", 100, ""),
    ("熙鳳", "person_wang_xifeng", "short_name", 100, ""),
    ("鳳姐", "person_wang_xifeng", "title_alias", 100, ""),
    ("鳳姐兒", "person_wang_xifeng", "title_alias", 100, ""),
    ("璉二奶奶", "person_wang_xifeng", "title_alias", 90, ""),
    ("賈母", "person_jia_mu", "title_alias", 100, ""),
    ("老太太", "person_jia_mu", "title_alias", 95, "可能泛指，需校對。"),
    ("史太君", "person_jia_mu", "formal_alias", 100, ""),
    ("湘雲", "person_shi_xiangyun", "short_name", 100, ""),
    ("史湘雲", "person_shi_xiangyun", "full_name", 100, ""),
    ("雲妹妹", "person_shi_xiangyun", "kinship_alias", 80, ""),
    ("妙玉", "person_miaoyu", "name", 100, ""),
    ("元春", "person_jia_yuanchun", "short_name", 100, ""),
    ("賈元春", "person_jia_yuanchun", "full_name", 100, ""),
    ("元妃", "person_jia_yuanchun", "title_alias", 95, ""),
    ("迎春", "person_jia_yingchun", "short_name", 100, ""),
    ("探春", "person_jia_tanchun", "short_name", 100, ""),
    ("惜春", "person_jia_xichun", "short_name", 100, ""),
    ("李紈", "person_li_wan", "full_name", 100, ""),
    ("稻香老農", "person_li_wan", "literary_alias", 80, ""),
    ("可卿", "person_qin_keqing", "short_name", 100, ""),
    ("秦可卿", "person_qin_keqing", "full_name", 100, ""),
    ("賈璉", "person_jia_lian", "full_name", 100, ""),
    ("璉二爺", "person_jia_lian", "title_alias", 100, ""),
    ("賈政", "person_jia_zheng", "full_name", 100, ""),
    ("政老爹", "person_jia_zheng", "title_alias", 90, ""),
    ("王夫人", "person_wang_furen", "title_alias", 100, ""),
    ("薛姨媽", "person_xue_yima", "title_alias", 100, ""),
    ("賈赦", "person_jia_she", "full_name", 100, ""),
    ("賈珍", "person_jia_zhen", "full_name", 100, ""),
    ("珍大爺", "person_jia_zhen", "title_alias", 90, ""),
    ("賈蓉", "person_jia_rong", "full_name", 100, ""),
    ("賈環", "person_jia_huan", "full_name", 100, ""),
    ("賈蘭", "person_jia_lan", "full_name", 100, ""),
    ("林如海", "person_lin_ruhai", "full_name", 100, ""),
    ("賈雨村", "person_jia_yucun", "full_name", 100, ""),
    ("雨村", "person_jia_yucun", "short_name", 100, ""),
    ("甄士隱", "person_zhen_shiyin", "full_name", 100, ""),
    ("士隱", "person_zhen_shiyin", "short_name", 100, ""),
    ("冷子興", "person_leng_zixing", "full_name", 100, ""),
    ("劉姥姥", "person_liu_laolao", "title_alias", 100, ""),
    ("襲人", "person_xiren", "name", 100, ""),
    ("晴雯", "person_qingwen", "name", 100, ""),
    ("麝月", "person_she_yue", "name", 100, ""),
    ("秋紋", "person_qiuwen", "name", 100, ""),
    ("紫鵑", "person_zijuan", "name", 100, ""),
    ("雪雁", "person_xueyan", "name", 100, ""),
    ("鶯兒", "person_ying_er", "name", 100, ""),
    ("平兒", "person_ping_er", "name", 100, ""),
    ("鴛鴦", "person_yuanyang", "name", 100, ""),
    ("司棋", "person_siqi", "name", 100, ""),
    ("侍書", "person_shishu", "name", 100, ""),
    ("入畫", "person_ruhua", "name", 100, ""),
    ("金釧", "person_jinchuan", "name", 100, ""),
    ("玉釧", "person_yuchuan", "name", 100, ""),
    ("香菱", "person_xiangling", "name", 100, ""),
    ("英蓮", "person_xiangling", "former_name", 100, ""),
    ("甄英蓮", "person_xiangling", "former_name", 100, ""),
    ("尤二姐", "person_you_erjie", "name", 100, ""),
    ("尤三姐", "person_you_sanjie", "name", 100, ""),
    ("尤氏", "person_you_shi", "name", 100, ""),
    ("趙姨娘", "person_zhao_yiniang", "title_alias", 100, ""),
    ("周瑞家的", "person_zhou_rui_jia", "servant_alias", 100, ""),
    ("賴大", "person_lai_da", "name", 100, ""),
]


RULE_ROWS = [
    # pattern, entity_type, subtype, match_type, priority, entity_key, notes
    ("通靈寶玉", "OBJECT", "symbolic_object", "exact", 100, "object_tongling_baoyu", ""),
    ("風月寶鑑", "OBJECT", "symbolic_object", "exact", 100, "object_fengyue_baojian", ""),
    ("大觀園", "PLACE", "garden", "exact", 100, "place_daguanyuan", ""),
    ("榮國府", "BUILDING", "mansion", "exact", 100, "building_rongguofu", ""),
    ("寧國府", "BUILDING", "mansion", "exact", 100, "building_ningguofu", ""),
    ("怡紅院", "BUILDING", "residence", "exact", 100, "building_yihongyuan", ""),
    ("瀟湘館", "BUILDING", "residence", "exact", 100, "building_xiaoxiangguan", ""),
    ("蘅蕪苑", "BUILDING", "residence", "exact", 100, "building_hengwuyuan", ""),
    ("秋爽齋", "BUILDING", "residence", "exact", 100, "building_qiushuangzhai", ""),
    ("稻香村", "BUILDING", "residence", "exact", 100, "building_daoxiangcun", ""),
    ("暖香塢", "BUILDING", "garden_space", "exact", 95, "building_nuanxiangwu", ""),
    ("櫳翠庵", "BUILDING", "temple", "exact", 100, "building_longcui_an", ""),
    ("鐵檻寺", "BUILDING", "temple", "exact", 90, "building_tiexian_si", ""),
    ("葫蘆廟", "BUILDING", "temple", "exact", 90, "building_hulu_miao", ""),
    ("書房", "ROOM_SPACE", "room", "exact", 70, "space_shufang", ""),
    ("內室", "ROOM_SPACE", "room", "exact", 70, "space_neishi", ""),
    ("廊下", "ROOM_SPACE", "corridor", "exact", 70, "space_langxia", ""),
    ("園子", "ROOM_SPACE", "garden_space", "exact", 60, "space_yuanzi", ""),
    ("海棠", "FLOWER", "flower", "exact", 85, "plant_haitang", ""),
    ("菊花", "FLOWER", "flower", "exact", 85, "plant_juhua", ""),
    ("芙蓉", "FLOWER", "flower", "exact", 85, "plant_furong", ""),
    ("桃花", "FLOWER", "flower", "exact", 80, "plant_taohua", ""),
    ("梅花", "FLOWER", "flower", "exact", 80, "plant_meihua", ""),
    ("牡丹", "FLOWER", "flower", "exact", 80, "plant_mudan", ""),
    ("蓮花", "FLOWER", "flower", "exact", 80, "plant_lian", ""),
    ("蓮", "FLOWER", "flower", "exact", 65, "plant_lian", "單字可能誤判，需校對。"),
    ("竹", "PLANT", "plant", "exact", 55, "plant_zhu", "單字可能誤判，需校對。"),
    ("柳", "PLANT", "plant", "exact", 55, "plant_liu", "單字可能誤判，需校對。"),
    ("薔薇", "FLOWER", "flower", "exact", 75, "plant_jiaoqiangwei", ""),
    ("紅", "COLOR", "basic_color", "exact", 50, "", "單字高歧義，僅作低優先規則。"),
    ("白", "COLOR", "basic_color", "exact", 50, "", "單字高歧義，僅作低優先規則。"),
    ("青", "COLOR", "basic_color", "exact", 50, "", "單字高歧義，僅作低優先規則。"),
    ("綠", "COLOR", "basic_color", "exact", 50, "", "單字高歧義，僅作低優先規則。"),
    ("紫", "COLOR", "basic_color", "exact", 50, "", "單字高歧義，僅作低優先規則。"),
    ("雪白", "COLOR", "compound_color", "exact", 70, "", ""),
    ("猩紅", "COLOR", "compound_color", "exact", 70, "", ""),
    ("石青", "COLOR", "compound_color", "exact", 70, "", ""),
    ("丫鬟", "TITLE_ROLE", "servant", "exact", 75, "", ""),
    ("小廝", "TITLE_ROLE", "servant", "exact", 75, "", ""),
    ("婆子", "TITLE_ROLE", "servant", "exact", 70, "", ""),
    ("奶娘", "TITLE_ROLE", "servant", "exact", 70, "", ""),
    ("太太", "TITLE_ROLE", "family_title", "exact", 65, "", ""),
    ("老爺", "TITLE_ROLE", "family_title", "exact", 65, "", ""),
    ("姑娘", "TITLE_ROLE", "family_title", "exact", 65, "", ""),
    ("姨娘", "TITLE_ROLE", "family_title", "exact", 65, "", ""),
    ("和尚", "TITLE_ROLE", "religious", "exact", 70, "", ""),
    ("道人", "TITLE_ROLE", "religious", "exact", 70, "", ""),
    ("王妃", "TITLE_ROLE", "court_title", "exact", 75, "", ""),
    ("妃", "TITLE_ROLE", "court_title", "exact", 45, "", "單字高歧義，需校對。"),
    ("元宵", "TIME", "festival", "exact", 80, "", ""),
    ("中秋", "TIME", "festival", "exact", 80, "", ""),
    ("端陽", "TIME", "festival", "exact", 75, "", ""),
    ("三月十五", "TIME", "date", "exact", 80, "", ""),
    ("茶", "FOOD", "drink", "exact", 50, "", "單字高頻，需校對。"),
    ("酒", "FOOD", "drink", "exact", 50, "", "單字高頻，需校對。"),
    ("粥", "FOOD", "food", "exact", 55, "", ""),
    ("螃蟹", "FOOD", "food", "exact", 70, "", ""),
    ("人參養榮丸", "MEDICINE", "medicine", "exact", 90, "", ""),
    ("斗篷", "CLOTHING", "outerwear", "exact", 75, "", ""),
    ("裙", "CLOTHING", "clothing", "exact", 45, "", "單字高歧義，需校對。"),
    ("襖", "CLOTHING", "clothing", "exact", 60, "", ""),
    ("釵環", "CLOTHING", "ornament", "exact", 70, "", ""),
    ("香", "OBJECT", "fragrance", "exact", 35, "", "高歧義，後續可移入 motif。"),
    ("夢", "MOTIF", "dream", "exact", 40, "", "高歧義，建議後續另建 motif.csv。"),
    ("淚", "MOTIF", "tears", "exact", 40, "", "高歧義，建議後續另建 motif.csv。"),
    ("病", "MOTIF", "illness", "exact", 35, "", "高歧義，建議後續另建 motif.csv。"),
    ("玉", "OBJECT", "jade", "exact", 35, "object_yu", "高歧義，需與人物寶玉消歧。"),
]


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, object]]) -> None:
    with path.open("w", encoding="utf-8-sig", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    write_csv(
        AUTHORITY_CSV,
        ["entity_key", "canonical_name", "entity_type", "subtype", "description"],
        [
            {
                "entity_key": key,
                "canonical_name": name,
                "entity_type": entity_type,
                "subtype": subtype,
                "description": description,
            }
            for key, name, entity_type, subtype, description in AUTHORITY_ROWS
        ],
    )
    write_csv(
        ALIAS_CSV,
        ["alias", "entity_key", "alias_type", "priority", "notes"],
        [
            {
                "alias": alias,
                "entity_key": key,
                "alias_type": alias_type,
                "priority": priority,
                "notes": notes,
            }
            for alias, key, alias_type, priority, notes in ALIAS_ROWS
        ],
    )
    write_csv(
        RULE_CSV,
        ["pattern", "entity_type", "subtype", "match_type", "priority", "entity_key", "notes"],
        [
            {
                "pattern": pattern,
                "entity_type": entity_type,
                "subtype": subtype,
                "match_type": match_type,
                "priority": priority,
                "entity_key": key,
                "notes": notes,
            }
            for pattern, entity_type, subtype, match_type, priority, key, notes in RULE_ROWS
        ],
    )
    print(f"wrote {AUTHORITY_CSV}: {len(AUTHORITY_ROWS)} rows")
    print(f"wrote {ALIAS_CSV}: {len(ALIAS_ROWS)} rows")
    print(f"wrote {RULE_CSV}: {len(RULE_ROWS)} rows")


if __name__ == "__main__":
    main()
